# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev-sprint1

pool:
  vmImage: 'macos-latest'

name: $(Environment)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: CocoaPods@0
  displayName: "Install CocoaPods dependencies"
  inputs:
    workingDirectory: ios
    forceRepoUpdate: false

- task: InstallAppleCertificate@2
  displayName: "Install Apple Certificate"
  inputs:
    certSecureFile: 'Certificates.p12'
    certPwd: '$(CertificatePassword)'

- task: InstallAppleProvisioningProfile@1
  displayName: "Install Apple provisioning profile"
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'trac_tsa_hoc.mobileprovision'

- task: CacheBeta@1
  displayName: "Set versions"
  inputs:
    sourcePath: 'ios/ReactNativePipeline/Info.plist'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    printFile: true

- task: Xcode@5
  displayName: "Build Mobile Application"
  inputs:
    actions: 'build'
    configuration: '$(Environment)'
    sdk: 'iphoneos13.2'
    xcWorkspacePath: 'ios/TSA_MOB'
    scheme: 'ReactNativePipeline'
    packageApp: true
    exportPath: 'output/package'
    archivePath: 'output/archive'
    signingOption: 'auto'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_11.3.app/Contents/Developer'
